sonar.projectKey=Nirmal188_devops-node-app
sonar.organization=nirmal188
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/*,coverage/,allure-results/*